version: "3.2"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret123!
      - MSSQL_PID=Developer